name: app
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^2.19.0

dependencies:
  connectivity_plus: ^3.0.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  freezed_annotation: ^2.2.0
  go_router: ^6.0.3
  gql: ^0.14.1-alpha+1672756470474
  graphql: ^5.1.3
  graphql_flutter: ^5.1.2
  json_annotation: ^4.8.0
  path_provider: ^2.0.12
  uuid: ^3.0.7

dev_dependencies: 
  build_runner: ^2.3.3
  freezed: ^2.3.2
  graphql_codegen: ^0.12.0-beta.7
  json_serializable: ^6.6.1
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true